{{-if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-chart-gke.serviceAccountName" . }}
  labels:
    {{-include "helm-chart-gke.labels" . | nindent 4 }}
  {{-with .Values.serviceAccount.annotations }}
  annotations:
    {{-toYaml . | nindent 4 }}
  {{-end }}
{{-end }}
